"""
Shortcut story formatting - single source of truth.

All story creation should use these functions to ensure consistent formatting.

Format spec:
- Excerpts link to Intercom conversation, Jarvis org page, Jarvis user page
- Description includes category, count, percentage, samples, review checklist
- Footer identifies FeedForward as the generator
"""

import os
from typing import Optional

INTERCOM_APP_ID = os.getenv("INTERCOM_APP_ID", "2t3d8az2")


def format_excerpt(
    conversation_id: str,
    email: Optional[str] = None,
    excerpt: str = "",
    org_id: Optional[str] = None,
    user_id: Optional[str] = None,
    intercom_url: Optional[str] = None,
    jarvis_org_url: Optional[str] = None,
    jarvis_user_url: Optional[str] = None,
) -> str:
    """
    Format a conversation excerpt with linked metadata.

    Format: [email](intercom_url) | [Org](jarvis_org_url) | [User](jarvis_user_url)
    > excerpt text...

    Args:
        conversation_id: Intercom conversation ID
        email: Customer email address
        excerpt: Conversation excerpt text
        org_id: Tailwind org ID (for Jarvis URL)
        user_id: Tailwind user ID (for Jarvis URL)
        intercom_url: Pre-built Intercom URL (optional, will build if not provided)
        jarvis_org_url: Pre-built Jarvis org URL (optional)
        jarvis_user_url: Pre-built Jarvis user URL (optional)

    Returns:
        Formatted markdown string
    """
    parts = []

    # Build URLs if not provided
    if not intercom_url:
        intercom_url = f"https://app.intercom.com/a/apps/{INTERCOM_APP_ID}/inbox/inbox/conversation/{conversation_id}"

    if not jarvis_org_url and org_id:
        jarvis_org_url = f"https://jarvis.tailwind.ai/organizations/{org_id}"

    if not jarvis_user_url and org_id and user_id:
        jarvis_user_url = f"https://jarvis.tailwind.ai/organizations/{org_id}/users/{user_id}"

    # Email linked to Intercom conversation
    display_email = email or f"Conversation {conversation_id}"
    parts.append(f"[{display_email}]({intercom_url})")

    # Org linked to Jarvis
    if jarvis_org_url:
        parts.append(f"[Org]({jarvis_org_url})")

    # User linked to Jarvis
    if jarvis_user_url:
        parts.append(f"[User]({jarvis_user_url})")

    user_info = " | ".join(parts)
    excerpt_text = excerpt[:300] if excerpt else ""

    return f"{user_info}\n> {excerpt_text}"


def build_story_description(
    category: str,
    count: int,
    total: int,
    samples: list[dict],
    pipeline_name: str = "FeedForward Classification Pipeline",
    time_period: str = "Last 30 Days",
) -> str:
    """
    Build Shortcut story description with formatted excerpts.

    Args:
        category: Classification category name
        count: Number of conversations in this category
        total: Total conversations analyzed
        samples: List of sample conversation dicts with keys:
            - id: conversation ID
            - email: customer email (optional)
            - excerpt: conversation text
            - org_id: Tailwind org ID (optional)
            - user_id: Tailwind user ID (optional)
            - intercom_url: pre-built URL (optional)
            - jarvis_org_url: pre-built URL (optional)
            - jarvis_user_url: pre-built URL (optional)
        pipeline_name: Name of the generating pipeline
        time_period: Description of time period analyzed

    Returns:
        Formatted markdown description
    """
    pct = count / total * 100 if total > 0 else 0

    description = f"""## Classification Results ({time_period})

**Category**: {category}
**Count**: {count} ({pct:.1f}% of total)
**Total Conversations Analyzed**: {total}

---

## Sample Conversations

"""
    for i, sample in enumerate(samples[:5], 1):
        formatted = format_excerpt(
            conversation_id=sample.get("id", "unknown"),
            email=sample.get("email"),
            excerpt=sample.get("excerpt", ""),
            org_id=sample.get("org_id"),
            user_id=sample.get("user_id"),
            intercom_url=sample.get("intercom_url"),
            jarvis_org_url=sample.get("jarvis_org_url"),
            jarvis_user_url=sample.get("jarvis_user_url"),
        )
        description += f"### Sample {i}\n{formatted}\n\n"

    description += f"""---

## Review Checklist
- [ ] Classification accuracy looks correct
- [ ] Sample excerpts match the category
- [ ] No obvious misclassifications

---
*Generated by {pipeline_name}*
"""
    return description


def get_story_type(category: str) -> str:
    """
    Get Shortcut story type based on classification category.

    Args:
        category: Classification category name

    Returns:
        "bug", "feature", or "chore"
    """
    if category == "product_issue":
        return "bug"
    elif category == "feature_request":
        return "feature"
    else:
        return "chore"


def build_story_name(category: str, count: int, suffix: str = "Review") -> str:
    """
    Build consistent story name.

    Format: [count] Category Name - suffix

    Args:
        category: Classification category (snake_case)
        count: Number of conversations
        suffix: Story name suffix (default: "Review")

    Returns:
        Formatted story name
    """
    title = category.replace("_", " ").title()
    return f"[{count}] {title} - {suffix}"
